# Generated by Django 3.2.7 on 2022-01-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbr', '0001_squashed_0011_auto_20220102_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbr',
            old_name='candidate_Signature',
            new_name='signature',
        ),
    ]
