# Generated by Django 3.2.7 on 2022-01-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr', '0002_rename_candidate_signature_cbr_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbr',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbr',
            name='has_Certificate',
            field=models.BooleanField(default=False),
        ),
    ]
