# Generated by Django 3.2.7 on 2022-01-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr', '0003_auto_20220116_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbr',
            name='audit_Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbr',
            name='audit_Notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
