# Generated by Django 3.2.7 on 2022-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr', '0005_auto_20220102_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbr',
            name='eval_1',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_2',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_3',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_4',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_5',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_6',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_7',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_8',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbr',
            name='eval_9',
            field=models.CharField(blank=True, choices=[('review_1', '1'), ('review_2', '2'), ('review_3', '3'), ('review_4', '4'), ('review_5', '5')], max_length=10, null=True),
        ),
    ]
