# Generated by Django 3.2.7 on 2022-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr', '0007_auto_20220324_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbr',
            name='course_Duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
