# Generated by Django 3.2.7 on 2022-06-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loading_shovel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shovel',
            name='akDate',
        ),
        migrations.RemoveField(
            model_name='shovel',
            name='akFail',
        ),
        migrations.RemoveField(
            model_name='shovel',
            name='akPass',
        ),
        migrations.RemoveField(
            model_name='shovel',
            name='preUseDate',
        ),
        migrations.RemoveField(
            model_name='shovel',
            name='preUseFail',
        ),
        migrations.RemoveField(
            model_name='shovel',
            name='preUsePass',
        ),
    ]
