# Generated by Django 3.2.7 on 2022-06-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loading_shovel', '0002_auto_20220605_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shovel',
            name='platformN',
        ),
        migrations.RemoveField(
            model_name='shovel',
            name='platformY',
        ),
    ]
