# Generated by Django 3.2.7 on 2022-06-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loading_shovel', '0003_auto_20220605_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shovel',
            old_name='vehicle_Shovel',
            new_name='vehicle_Loading',
        ),
    ]
