# Generated by Django 3.2.7 on 2022-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivot_steer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivot',
            name='machine_Test_Load_Centre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
