# Generated by Django 3.2.7 on 2022-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivot_steer', '0002_pivot_machine_test_load_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivot',
            name='attachments',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
