# Generated by Django 3.2.7 on 2022-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivot_steer', '0003_pivot_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pivot',
            name='axles',
        ),
        migrations.RemoveField(
            model_name='pivot',
            name='equipment_Type',
        ),
        migrations.RemoveField(
            model_name='pivot',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='pivot',
            name='group2',
        ),
        migrations.RemoveField(
            model_name='pivot',
            name='platform2',
        ),
        migrations.RemoveField(
            model_name='pivot',
            name='stabilisers',
        ),
        migrations.AlterField(
            model_name='pivot',
            name='machine_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
