# Generated by Django 3.2.7 on 2022-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivot_steer', '0004_auto_20220528_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pivot',
            old_name='highway',
            new_name='attachments_Init',
        ),
        migrations.RenameField(
            model_name='pivot',
            old_name='mewpS',
            new_name='eye_Level',
        ),
        migrations.RenameField(
            model_name='pivot',
            old_name='park_Bays',
            new_name='fts',
        ),
        migrations.RenameField(
            model_name='pivot',
            old_name='side_Mid_Level',
            new_name='low_Level',
        ),
        migrations.AddField(
            model_name='pivot',
            name='ramps',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pivot',
            name='rider_Pedestrian',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pivot',
            name='vehicle_Loading',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pivot',
            name='vert_Face',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
