# Generated by Django 3.2.7 on 2022-06-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threesixty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threesixty',
            old_name='tenching',
            new_name='trenching',
        ),
    ]
