# Generated by Django 3.2.7 on 2021-10-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='candidateNumber',
            new_name='candidate_number',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courseNumber',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courseType',
            new_name='course_type',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
