# Generated by Django 3.2.7 on 2021-11-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_address', models.CharField(max_length=150, unique=True)),
                ('company_contact', models.CharField(max_length=50, unique=True)),
                ('company_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
