# Generated by Django 3.2.7 on 2022-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20211102_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
