# Generated by Django 3.2.7 on 2022-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customers_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='company_address',
            new_name='company_address_city',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='company_contact',
            new_name='company_contact_first_name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='company_number',
            new_name='company_fax_number',
        ),
        migrations.AddField(
            model_name='customers',
            name='company_address_county',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_address_line_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_address_line_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_address_line_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_address_line_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_address_post_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_contact_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_ddi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='company_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
