# Generated by Django 3.2.7 on 2022-02-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aw',
            old_name='benchMounted',
            new_name='bench_Mounted',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='petrolDriven',
            new_name='petrol_Driven',
        ),
    ]
