# Generated by Django 3.2.7 on 2022-02-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0002_auto_20220220_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aw',
            old_name='basicSkills',
            new_name='basic_Skills',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='preShift',
            new_name='pre_Shift',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='preUsePoints',
            new_name='pre_Use_Test',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='refresherTest',
            new_name='refresher_Test',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='specificJob',
            new_name='specific_Job',
        ),
    ]
