# Generated by Django 3.2.7 on 2022-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0004_auto_20220220_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='aw',
            name='d1_LC',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
