# Generated by Django 3.2.7 on 2022-02-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0005_aw_d1_lc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aw',
            old_name='courseTiming',
            new_name='course_Timing',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='finishTime',
            new_name='finish_Time',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='setTime',
            new_name='set_Time',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='startTime',
            new_name='start_Time',
        ),
        migrations.RenameField(
            model_name='aw',
            old_name='trainingRatio',
            new_name='training_Ratio',
        ),
    ]
