# Generated by Django 3.2.7 on 2022-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0007_alter_aw_instructor_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aw',
            name='bMachineGroup',
        ),
        migrations.AlterField(
            model_name='aw',
            name='machine_Group',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
