# Generated by Django 3.2.7 on 2022-02-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='attachmentsInitial',
            new_name='attachments_Initial',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='courseTiming',
            new_name='course_Timing',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='finalGrading',
            new_name='final_Grading',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='machineMakeModel',
            new_name='machine_Make_Model',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='preUsePoints',
            new_name='preUse_Points',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='specialApplication',
            new_name='special_Application',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='theoryPaperNumber',
            new_name='theory_Paper_Number',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='theoryTestDate',
            new_name='theory_Test_Date',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='trainingRatio',
            new_name='training_Ratio',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='vehicleLoading',
            new_name='vehicle_Loading',
        ),
    ]
