# Generated by Django 3.2.7 on 2022-02-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppt', '0002_auto_20220227_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='finishTime',
            new_name='finish_Time',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='setTime',
            new_name='load_Centre',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='startTime',
            new_name='start_Time',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='testDate',
            new_name='test_Date',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='testFail',
            new_name='test_Fail',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='testPass',
            new_name='test_Pass',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='height',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='loadCentre',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='machineCapacity',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='machineGroup',
        ),
        migrations.AddField(
            model_name='ppt',
            name='machine_Capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppt',
            name='machine_Test_Lift_Height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppt',
            name='set_Time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='instructor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pptInstructor2', to=settings.AUTH_USER_MODEL),
        ),
    ]
