# Generated by Django 3.2.7 on 2022-02-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0004_ppt_machine_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='akRefer',
            new_name='akFail',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='preUseRefer',
            new_name='preUseFail',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='group',
        ),
    ]
