# Generated by Django 3.2.7 on 2022-02-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0005_auto_20220227_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='candidateDOB',
            new_name='candidate_DOB',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='courseDuration',
            new_name='course_Duration',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='courseTitle',
            new_name='course_Title',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='topsId',
        ),
    ]
