# Generated by Django 3.2.7 on 2022-02-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0006_auto_20220227_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='liftHeightCapacity',
            new_name='machine_Type',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='machineMotivePower',
            new_name='motive_Power',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='liftHeightCapacity2',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='machineType',
        ),
    ]
