# Generated by Django 3.2.7 on 2022-02-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0007_auto_20220227_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='basicSkills',
            new_name='basic_Skills',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='preShift',
            new_name='pre_Shift',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='refresherTest',
            new_name='refresher_Test',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='riderPedestrian',
            new_name='rider_Pedestrian',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='specificJob',
            new_name='specific_Job',
        ),
        migrations.RemoveField(
            model_name='ppt',
            name='attachments2',
        ),
    ]
