# Generated by Django 3.2.7 on 2022-02-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0008_auto_20220227_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='eyeLevel',
            new_name='eye_Level',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='highLevel',
            new_name='high_Level',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='lowLevel',
            new_name='low_Level',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='vertFace',
            new_name='vert_Face',
        ),
    ]
