# Generated by Django 3.2.7 on 2022-04-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0010_auto_20220227_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='motive_Power',
            new_name='machine_Motive_Power',
        ),
    ]
