# Generated by Django 3.2.7 on 2022-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0011_rename_motive_power_ppt_machine_motive_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='machine_Make_Model',
            new_name='machine_Make',
        ),
        migrations.AddField(
            model_name='ppt',
            name='machine_Model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
