# Generated by Django 3.2.7 on 2022-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boom',
            name='preUseEM_31',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
