# Generated by Django 3.2.7 on 2022-02-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohc',
            old_name='courseTitle',
            new_name='course_Title',
        ),
        migrations.RemoveField(
            model_name='ohc',
            name='crane_Make',
        ),
        migrations.RemoveField(
            model_name='ohc',
            name='crane_Model',
        ),
        migrations.RemoveField(
            model_name='ohc',
            name='organisation',
        ),
    ]
