# Generated by Django 3.2.7 on 2022-02-13 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211024_1554'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ohc', '0002_auto_20220213_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohc',
            name='candidate_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ohc',
            name='course_Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ohcCourse', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='ohc',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ohcInstructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
