# Generated by Django 3.2.7 on 2022-02-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ohc', '0003_auto_20220213_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohc',
            name='instructor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ohcInstructor2', to=settings.AUTH_USER_MODEL),
        ),
    ]
