# Generated by Django 3.2.7 on 2022-02-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211024_1554'),
        ('mewp', '0002_auto_20220201_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='candidate_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='course_Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mewpCourse', to='courses.courses'),
        ),
    ]
