# Generated by Django 3.2.7 on 2022-02-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0003_auto_20220201_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mewp',
            old_name='finishTime',
            new_name='finish_Time',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='setTime',
            new_name='set_Time',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='startTime',
            new_name='start_Time',
        ),
    ]
