# Generated by Django 3.2.7 on 2022-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0004_auto_20220201_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='mewp',
            name='penalty_32',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
