# Generated by Django 3.2.7 on 2022-02-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0005_mewp_penalty_32'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mewp',
            old_name='basicSkills',
            new_name='basic_Skills',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='highLevel',
            new_name='high_Level',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='machineGroup',
            new_name='machine_Group',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='machineType',
            new_name='machine_Type',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='parkBays',
            new_name='park_Bays',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='preShift',
            new_name='pre_Shift',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='refresherTest',
            new_name='refresher_Test',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='sideMidLevel',
            new_name='side_Mid_Level',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='liftHeightCapacity',
            new_name='special_Application',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='specificJob',
            new_name='specific_Job',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='liftHeightCapacity2',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='motivePower',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='specialApplication',
        ),
        migrations.AlterField(
            model_name='mewp',
            name='machine_Capacity',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='machine_Test_Lift_Height',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
