# Generated by Django 3.2.7 on 2022-02-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0006_auto_20220206_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mewp',
            old_name='finalGrading',
            new_name='final_Grading',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='instructorComments',
            new_name='instructor_Comments',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='preUsePoints',
            new_name='pre_Use_Test',
        ),
        migrations.RenameField(
            model_name='mewp',
            old_name='theoryPaperNumber',
            new_name='theory_Paper_Number',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='BO_capacity',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='BO_liftHeight',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='BO_truckModel',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='BO_truckType',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='theoryTestDate',
        ),
        migrations.AddField(
            model_name='mewp',
            name='theory_Test_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
