# Generated by Django 3.2.7 on 2022-02-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0008_auto_20220208_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='machine_Capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='machine_Test_Lift_Height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
